## These functions serve the purpose of avoid repetiting of lengthy
# computation of matrix inverses. If the inverse of a user supplied
# nonsingular matrix has already been computed, the result is retrieved
# from cache rather computation repeated.

## 'makeCacheMatrix':Creates a special matrix that can cache its inverse. 
# Specifically is composed by a vector of for functions: 
# 1) iset: sets the matrix 2) iget: returns the matrix 
# 3) setinv: sets the inverse. 4) getinv: returns the inverse

makeCacheMatrix <- function(M = matrix()) {
        I    <- NULL
        iset  <- function(y) {
                M <<- y
                I <<- NULL
        }
        iget   <- function() M
        setinv <- function(Inv) I <<- Inv
        getinv <- function() I
        list(iset = iset, iget = iget,
             setinv = setinv,
             getinv = getinv)
}


## 'cacheSolve':Computes the inverse of the matrix object generated by 
# makeCacheMatrix. If the inverse has already been calculated, 
# it is retrieved fro cache. 

cacheSolve <- function(x, ...) {
        I <- x$getinv()
        if(!is.null(I)) {
                message("getting cached data")
                return(I)
        }
        data <- x$iget()
        Inv  <- solve(data, ...)
        x$setinv(Inv)
        Inv
}
